import {
  BadRequestException,
  ConflictException,
  GoneException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { AcademyRole, Prisma } from '@prisma/client';
import { createHash, randomBytes } from 'crypto';
import { PrismaService } from '../prisma/prisma.service';
import { assertStaffEligible } from './permissions';

const TOKEN_BYTES = 32;
const DEFAULT_TTL_DAYS = 14;

const GONE = () =>
  new GoneException({
    message: 'This invitation link is no longer valid',
    code: 'INVITATION_LINK_INVALID',
  });

/**
 * A shareable, single-use staff invitation for one Center + one role — the
 * link counterpart to the existing email invite (addMember). Generated by an
 * OWNER for their own Center; redeemed by whoever the OWNER shares it with,
 * once, before it expires, is revoked, or is declined. academyId and role
 * always come from the stored row, never from the redeemer.
 */
@Injectable()
export class InvitationLinksService {
  constructor(private readonly prisma: PrismaService) {}

  private hash(token: string): string {
    return createHash('sha256').update(token).digest('hex');
  }

  async create(academyId: string, createdByUserId: string, role: AcademyRole) {
    const raw = randomBytes(TOKEN_BYTES).toString('base64url');
    const expiresAt = new Date(Date.now() + DEFAULT_TTL_DAYS * 86_400_000);
    const row = await this.prisma.academyInvitationLink.create({
      data: { academyId, role, tokenHash: this.hash(raw), createdByUserId, expiresAt },
      select: { id: true, role: true, expiresAt: true, createdAt: true },
    });
    // The raw token is returned exactly once, here — never persisted, never logged.
    return { ...row, token: raw };
  }

  async list(academyId: string) {
    const rows = await this.prisma.academyInvitationLink.findMany({
      where: { academyId },
      orderBy: { createdAt: 'desc' },
      select: {
        id: true,
        role: true,
        expiresAt: true,
        usedAt: true,
        revokedAt: true,
        declinedAt: true,
        createdAt: true,
        createdByUserId: true,
      },
    });
    const now = new Date();
    return rows.map((r) => ({
      ...r,
      status: r.usedAt
        ? 'USED'
        : r.revokedAt
          ? 'REVOKED'
          : r.declinedAt
            ? 'DECLINED'
            : r.expiresAt <= now
              ? 'EXPIRED'
              : 'PENDING',
    }));
  }

  async revoke(academyId: string, id: string) {
    const row = await this.prisma.academyInvitationLink.findFirst({ where: { id, academyId } });
    if (!row) throw new NotFoundException('Invitation link not found');
    if (row.usedAt)
      throw new BadRequestException({ message: 'Already used', code: 'ALREADY_USED' });
    if (row.revokedAt) return { id, revoked: true };
    await this.prisma.academyInvitationLink.update({
      where: { id },
      data: { revokedAt: new Date() },
    });
    return { id, revoked: true };
  }

  /** What the invitee sees before deciding — nothing that isn't already implied by the link. */
  async preview(token: string) {
    const row = await this.resolveLive(token);
    return { academyName: row.academy.name, role: row.role, expiresAt: row.expiresAt };
  }

  /**
   * Explicit accept by an existing account. Eligibility is checked BEFORE the
   * token is claimed, so an ineligible account probing a real link cannot burn
   * it for the intended recipient. The claim itself is one conditional update
   * — two concurrent accepts cannot both succeed — and everything the
   * membership gets (academyId, role) comes from the row the token was issued
   * for.
   *
   * Replaying an accept the SAME user already won is answered with their
   * membership, not an error — a retried request must not read as a failure.
   * Anyone else hitting a used link gets 410: a consumed invitation never
   * transfers.
   */
  async accept(token: string, userId: string) {
    const replay = await this.replayFor(token, userId);
    if (replay) return replay;

    const row = await this.resolveLive(token);
    const user = await this.prisma.user.findUniqueOrThrow({
      where: { id: userId },
      select: { role: true, isActive: true, teacherProfile: { select: { status: true } } },
    });
    assertStaffEligible(user, row.role);

    const claimed = await this.prisma.academyInvitationLink.updateMany({
      where: this.claimable(row.tokenHash),
      data: { usedAt: new Date(), usedByUserId: userId },
    });
    if (claimed.count !== 1) throw GONE();

    const existing = await this.prisma.academyMembership.findUnique({
      where: { userId_academyId: { userId, academyId: row.academyId } },
    });
    if (existing?.status === 'ACTIVE') {
      throw new ConflictException({
        message: 'Already a member of this Center',
        code: 'ALREADY_MEMBER',
      });
    }
    // No row, or LEFT/INVITED/SUSPENDED: an explicit accept is exactly the
    // consent the re-invitation lifecycle requires — creates or reactivates
    // straight to ACTIVE, never through the generic member-update path.
    return this.prisma.academyMembership.upsert({
      where: { userId_academyId: { userId, academyId: row.academyId } },
      update: { role: row.role, status: 'ACTIVE', joinedAt: new Date() },
      create: {
        userId,
        academyId: row.academyId,
        role: row.role,
        status: 'ACTIVE',
        joinedAt: new Date(),
      },
      select: { id: true, academyId: true, role: true, status: true },
    });
  }

  /**
   * The invitee's explicit "no". Closes the link for good — the owner sees
   * DECLINED and issues a new one if they want to ask again — and writes
   * nothing else: no membership row of any status is created by a refusal.
   * Idempotent for the person who declined; 410 for everyone else once closed.
   */
  async decline(token: string, userId: string) {
    const tokenHash = this.hash(token);
    const row = await this.prisma.academyInvitationLink.findUnique({
      where: { tokenHash },
      select: { id: true, academyId: true, role: true, declinedAt: true, declinedByUserId: true },
    });
    if (!row) throw new NotFoundException('Invitation link not found');
    const closed = await this.prisma.academyInvitationLink.updateMany({
      where: this.claimable(tokenHash),
      data: { declinedAt: new Date(), declinedByUserId: userId },
    });
    if (closed.count !== 1 && !(row.declinedAt && row.declinedByUserId === userId)) throw GONE();
    return { id: row.id, academyId: row.academyId, role: row.role, declined: true as const };
  }

  /**
   * The claim half of a brand-new account's registration, run inside the same
   * transaction that creates the account: if the link cannot be claimed the
   * whole registration rolls back, so a dead link never leaves a stray user
   * behind. The membership is built from the row the token names — the
   * caller supplies only the userId it just created.
   */
  async claimForNewUser(tx: Prisma.TransactionClient, tokenHash: string, userId: string) {
    const now = new Date();
    const claimed = await tx.academyInvitationLink.updateMany({
      where: this.claimable(tokenHash),
      data: { usedAt: now, usedByUserId: userId },
    });
    if (claimed.count !== 1) throw GONE();
    const row = await tx.academyInvitationLink.findUniqueOrThrow({
      where: { tokenHash },
      select: { academyId: true, role: true },
    });
    return tx.academyMembership.create({
      data: { userId, academyId: row.academyId, role: row.role, status: 'ACTIVE', joinedAt: now },
      select: { id: true, academyId: true, role: true, status: true },
    });
  }

  /** A live link, or the reason it is not. Public so registration can resolve the same way accept does. */
  async resolveLive(token: string) {
    const row = await this.prisma.academyInvitationLink.findUnique({
      where: { tokenHash: this.hash(token) },
      select: {
        tokenHash: true,
        role: true,
        academyId: true,
        expiresAt: true,
        usedAt: true,
        revokedAt: true,
        declinedAt: true,
        academy: { select: { name: true, status: true, deletedAt: true } },
      },
    });
    if (!row) throw new NotFoundException('Invitation link not found');
    if (row.usedAt || row.revokedAt || row.declinedAt || row.expiresAt <= new Date()) throw GONE();
    if (
      row.academy.deletedAt ||
      row.academy.status === 'SUSPENDED' ||
      row.academy.status === 'ARCHIVED'
    )
      throw GONE();
    return row;
  }

  /** The one predicate every claim/decline is bound to: exactly this row, still open, still in date. */
  private claimable(tokenHash: string): Prisma.AcademyInvitationLinkWhereInput {
    return {
      tokenHash,
      usedAt: null,
      revokedAt: null,
      declinedAt: null,
      expiresAt: { gt: new Date() },
    };
  }

  /** The membership this user already won with this exact link, if that is what happened. */
  private async replayFor(token: string, userId: string) {
    const used = await this.prisma.academyInvitationLink.findUnique({
      where: { tokenHash: this.hash(token) },
      select: { usedAt: true, usedByUserId: true, academyId: true },
    });
    if (!used?.usedAt || used.usedByUserId !== userId) return null;
    const membership = await this.prisma.academyMembership.findFirst({
      where: { userId, academyId: used.academyId, status: 'ACTIVE', deletedAt: null },
      select: { id: true, academyId: true, role: true, status: true },
    });
    return membership ?? null;
  }
}
